# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(489, 100)
        self.lbl_link = QtWidgets.QTextBrowser(Form1)
        self.lbl_link.setGeometry(QtCore.QRect(20, 30, 256, 31))
        self.lbl_link.setObjectName("lbl_link")
        self.btn_submit = QtWidgets.QPushButton(Form1)
        self.btn_submit.setGeometry(QtCore.QRect(380, 30, 75, 31))
        self.btn_submit.setObjectName("btn_submit")
        self.btn_select_file = QtWidgets.QPushButton(Form1)
        self.btn_select_file.setGeometry(QtCore.QRect(290, 30, 75, 31))
        self.btn_select_file.setObjectName("btn_select_file")

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Form"))
        self.btn_submit.setText(_translate("Form1", "Submit"))
        self.btn_select_file.setText(_translate("Form1", "Select File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.show()
    sys.exit(app.exec_())
