# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 659)
        MainWindow.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(170, 600))
        self.frame.setStyleSheet("QFrame#frame{\n"
" background-color: rgb(210, 200, 200);\n"
"}\n"
"QPushButton#btn1{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(110, 145, 223);}\n"
"QPushButton#btn1:hover{\n"
"background-color:  rgb(202, 168, 107);}\n"
"QPushButton#btn1:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(202, 168, 107);}\n"
"\n"
"QPushButton#btn2{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(110, 145, 223);}\n"
"QPushButton#btn2:hover{\n"
"background-color:  rgb(202, 168, 107);}\n"
"QPushButton#btn2:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(202, 168, 107);}\n"
"\n"
"QPushButton#btn3{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(110, 145, 223);}\n"
"QPushButton#btn3:hover{\n"
"background-color:  rgb(202, 168, 107);}\n"
"QPushButton#btn3:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(202, 168, 107);}\n"
"\n"
"QPushButton#btn4{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(110, 145, 223);}\n"
"QPushButton#btn4:hover{\n"
"background-color:  rgb(202, 168, 107);}\n"
"QPushButton#btn4:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(202, 168, 107);}\n"
"\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.btn1 = QtWidgets.QPushButton(self.frame)
        self.btn1.setEnabled(True)
        self.btn1.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("")
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 0, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.frame)
        self.btn2.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn2.setFont(font)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 1, 0, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.frame)
        self.btn3.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn3.setFont(font)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 2, 0, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.frame)
        self.btn4.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn4.setFont(font)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label = QtWidgets.QLabel(self.page_home)
        self.label.setGeometry(QtCore.QRect(0, 190, 701, 181))
        font = QtGui.QFont()
        font.setFamily("Harrington")
        font.setPointSize(26)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.page_home)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("QStackedWidget#stackedWidget{\n"
"background-color: rgb(217, 217, 217);\n"
"}\n"
"QFrame#frame{\n"
" background-color: rgb(210, 200, 200);\n"
"}\n"
"QPushButton#btn1_1{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn1_1:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn1_1:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn1_2{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color:rgb(202, 168, 107);}\n"
"QPushButton#btn1_2:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn1_2:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn1_3{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn1_3:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn1_3:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn1_4{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn1_4:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn1_4:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"\n"
"")
        self.page_1.setObjectName("page_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.table_excel = QtWidgets.QTableWidget(self.page_1)
        self.table_excel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_excel.sizePolicy().hasHeightForWidth())
        self.table_excel.setSizePolicy(sizePolicy)
        self.table_excel.setMinimumSize(QtCore.QSize(500, 500))
        self.table_excel.setObjectName("table_excel")
        self.table_excel.setColumnCount(0)
        self.table_excel.setRowCount(0)
        self.gridLayout_4.addWidget(self.table_excel, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn1_3 = QtWidgets.QPushButton(self.page_1)
        self.btn1_3.setMinimumSize(QtCore.QSize(50, 30))
        self.btn1_3.setObjectName("btn1_3")
        self.gridLayout_2.addWidget(self.btn1_3, 0, 2, 1, 1)
        self.btn1_4 = QtWidgets.QPushButton(self.page_1)
        self.btn1_4.setMinimumSize(QtCore.QSize(50, 30))
        self.btn1_4.setObjectName("btn1_4")
        self.gridLayout_2.addWidget(self.btn1_4, 0, 3, 1, 1)
        self.btn1_2 = QtWidgets.QPushButton(self.page_1)
        self.btn1_2.setMinimumSize(QtCore.QSize(50, 30))
        self.btn1_2.setObjectName("btn1_2")
        self.gridLayout_2.addWidget(self.btn1_2, 0, 1, 1, 1)
        self.btn1_1 = QtWidgets.QPushButton(self.page_1)
        self.btn1_1.setMinimumSize(QtCore.QSize(50, 30))
        self.btn1_1.setObjectName("btn1_1")
        self.gridLayout_2.addWidget(self.btn1_1, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("\n"
"QPushButton#btn2_1{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn2_1:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn2_1:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn2_2{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color:rgb(202, 168, 107);}\n"
"QPushButton#btn2_2:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn2_2:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn2_3{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn2_3:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn2_3:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn2_4{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn2_4:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn2_4:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}\n"
"\n"
"QPushButton#btn2_5{\n"
"         color: rgba(0, 0, 0, 150);\n"
"         background-color: rgb(202, 168, 107);}\n"
"QPushButton#btn2_5:hover{\n"
"background-color:  rgb(201, 131, 106);}\n"
"QPushButton#btn2_5:pressed{\n"
" padding-left: 2px;\n"
" padding-top: 2px;\n"
" background-color: rgb(201, 131, 106);}")
        self.page_2.setObjectName("page_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn2_1 = QtWidgets.QPushButton(self.page_2)
        self.btn2_1.setMinimumSize(QtCore.QSize(50, 30))
        self.btn2_1.setObjectName("btn2_1")
        self.gridLayout_5.addWidget(self.btn2_1, 0, 0, 1, 1)
        self.btn2_2 = QtWidgets.QPushButton(self.page_2)
        self.btn2_2.setMinimumSize(QtCore.QSize(50, 30))
        self.btn2_2.setObjectName("btn2_2")
        self.gridLayout_5.addWidget(self.btn2_2, 0, 1, 1, 1)
        self.btn2_3 = QtWidgets.QPushButton(self.page_2)
        self.btn2_3.setMinimumSize(QtCore.QSize(50, 30))
        self.btn2_3.setObjectName("btn2_3")
        self.gridLayout_5.addWidget(self.btn2_3, 0, 2, 1, 1)
        self.btn2_4 = QtWidgets.QPushButton(self.page_2)
        self.btn2_4.setMinimumSize(QtCore.QSize(50, 30))
        self.btn2_4.setObjectName("btn2_4")
        self.gridLayout_5.addWidget(self.btn2_4, 0, 3, 1, 1)
        self.btn2_5 = QtWidgets.QPushButton(self.page_2)
        self.btn2_5.setMinimumSize(QtCore.QSize(50, 30))
        self.btn2_5.setObjectName("btn2_5")
        self.gridLayout_5.addWidget(self.btn2_5, 0, 4, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.frame_btn1_2 = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btn1_2.sizePolicy().hasHeightForWidth())
        self.frame_btn1_2.setSizePolicy(sizePolicy)
        self.frame_btn1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn1_2.setObjectName("frame_btn1_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_btn1_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.table_excel_2 = QtWidgets.QTableWidget(self.frame_btn1_2)
        self.table_excel_2.setObjectName("table_excel_2")
        self.table_excel_2.setColumnCount(0)
        self.table_excel_2.setRowCount(0)
        self.gridLayout_6.addWidget(self.table_excel_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_btn1_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scropper"))
        self.btn1.setText(_translate("MainWindow", "Button1"))
        self.btn2.setText(_translate("MainWindow", "Button2"))
        self.btn3.setText(_translate("MainWindow", "Dropbox"))
        self.btn4.setText(_translate("MainWindow", "S_mart"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600; color:#6e91df;\">Scropper</span></p></body></html>"))
        self.btn1_3.setText(_translate("MainWindow", "追加/更新判定"))
        self.btn1_4.setText(_translate("MainWindow", "加工へ送る"))
        self.btn1_2.setText(_translate("MainWindow", "MDBで検索"))
        self.btn1_1.setText(_translate("MainWindow", "Excelからインポート"))
        self.btn2_1.setText(_translate("MainWindow", "画像加工"))
        self.btn2_2.setText(_translate("MainWindow", "テキスト加工"))
        self.btn2_3.setText(_translate("MainWindow", "エクスポート"))
        self.btn2_4.setText(_translate("MainWindow", "Dropboxアップロード"))
        self.btn2_5.setText(_translate("MainWindow", "S_Martアップロード"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
